@ModuleEndpoint = {{ Host }}/auth

### Create an user
POST {{ ModuleEndpoint }}/local/signup
Content-Type: application/json

{
	"email": "email@gmail.com",
	"password": "secretpassword"
}

### Sign in an user
POST {{ ModuleEndpoint }}/local/signin
Content-Type: application/json

{
	"email": "{{ currentUserEmail }}",
	"password": "{{ currentPassword }}"
}

### Log out an user
POST {{ ModuleEndpoint }}/logout
Authorization: Bearer {{ currentAccessToken }}

### Refresh user's token
POST {{ ModuleEndpoint }}/refresh
Authorization: Bearer {{ currentRefreshToken }}